package dxgi

// DXGI_ADAPTER_FLAG
const (
	DXGI_STATUS_OCCLUDED                     = 1
	DXGI_STATUS_CLIPPED                      = 2
	DXGI_STATUS_NO_REDIRECTION               = 4
	DXGI_STATUS_NO_DESKTOP_ACCESS            = 5
	DXGI_STATUS_GRAPHICS_VIDPN_SOURCE_IN_USE = 6
	DXGI_STATUS_MODE_CHANGED                 = 7
	DXGI_STATUS_MODE_CHANGE_IN_PROGRESS      = 8
)

// DXGI_MODE_ROTATION
const (
	DXGI_MODE_ROTATION_UNSPECIFIED = 0
	DXGI_MODE_ROTATION_IDENTITY    = 1
	DXGI_MODE_ROTATION_ROTATE90    = 2
	DXGI_MODE_ROTATION_ROTATE180   = 3
	DXGI_MODE_ROTATION_ROTATE270   = 4
)

const (
	DXGI_ERROR_INVALID_CALL                 = 1
	DXGI_ERROR_NOT_FOUND                    = 2
	DXGI_ERROR_MORE_DATA                    = 3
	DXGI_ERROR_UNSUPPORTED                  = 4
	DXGI_ERROR_DEVICE_REMOVED               = 5
	DXGI_ERROR_DEVICE_HUNG                  = 6
	DXGI_ERROR_DEVICE_RESET                 = 7
	DXGI_ERROR_WAS_STILL_DRAWING            = 10
	DXGI_ERROR_FRAME_STATISTICS_DISJOINT    = 11
	DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE = 12
	DXGI_ERROR_DRIVER_INTERNAL_ERROR        = 32
	DXGI_ERROR_NONEXCLUSIVE                 = 33
	DXGI_ERROR_NOT_CURRENTLY_AVAILABLE      = 34
	DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED   = 35
	DXGI_ERROR_REMOTE_OUTOFMEMORY           = 36
)

const (
	DXGI_CPU_ACCESS_NONE            = 0
	DXGI_CPU_ACCESS_DYNAMIC         = 1
	DXGI_CPU_ACCESS_READ_WRITE      = 2
	DXGI_CPU_ACCESS_SCRATCH         = 3
	DXGI_CPU_ACCESS_FIELD           = 15
	DXGI_USAGE_SHADER_INPUT         = 1 << (0 + 4)
	DXGI_USAGE_RENDER_TARGET_OUTPUT = 1 << (1 + 4)
	DXGI_USAGE_BACK_BUFFER          = 1 << (2 + 4)
	DXGI_USAGE_SHARED               = 1 << (3 + 4)
	DXGI_USAGE_READ_ONLY            = 1 << (4 + 4)
	DXGI_USAGE_DISCARD_ON_PRESENT   = 1 << (5 + 4)
	DXGI_USAGE_UNORDERED_ACCESS     = 1 << (6 + 4)
)

const (
	DXGI_MAX_SWAP_CHAIN_BUFFERS  = 16
	DXGI_PRESENT_TEST            = uint32(0x00000001)
	DXGI_PRESENT_DO_NOT_SEQUENCE = uint32(0x00000002)
	DXGI_PRESENT_RESTART         = uint32(0x00000004)
)

const (
	DXGI_MWA_NO_WINDOW_CHANGES = 1 << 0
	DXGI_MWA_NO_ALT_ENTER      = 1 << 1
	DXGI_MWA_NO_PRINT_SCREEN   = 1 << 2
	DXGI_MWA_VALID             = 0x7
)
