package dxgi

import (
	"testing"
)

func TestDXGI_ADAPTER_FLAG(t *testing.T) {
	if DXGI_ADAPTER_FLAG.DXGI_ADAPTER_FLAG_NONE != 0 {
		t.Error("DXGI_ADAPTER_FLAG_NONE should be 0")
	}
	if DXGI_ADAPTER_FLAG.DXGI_ADAPTER_FLAG_REMOTE != 1 {
		t.Error("DXGI_ADAPTER_FLAG_REMOTE should be 1")
	}
	if DXGI_ADAPTER_FLAG.DXGI_ADAPTER_FLAG_SOFTWARE != 2 {
		t.Error("DXGI_ADAPTER_FLAG_SOFTWARE should be 2")
	}
}

func TestDXGI_SWAP_EFFECT(t *testing.T) {
	if DXGI_SWAP_EFFECT.DXGI_SWAP_EFFECT_DISCARD != 1 {
		t.Error("DXGI_SWAP_EFFECT_DISCARD should be 1")
	}
	if DXGI_SWAP_EFFECT.DXGI_SWAP_EFFECT_FLIP_DISCARD != 4 {
		t.Error("DXGI_SWAP_EFFECT_FLIP_DISCARD should be 4")
	}
}

func TestDXGI_SWAP_CHAIN_FLAG(t *testing.T) {
	if DXGI_SWAP_CHAIN_FLAG.DXGI_SWAP_CHAIN_FLAG_NONPREROTATED != 1 {
		t.Error("DXGI_SWAP_CHAIN_FLAG_NONPREROTATED should be 1")
	}
	if DXGI_SWAP_CHAIN_FLAG.DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING != 2048 {
		t.Error("DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING should be 2048")
	}
}

func TestDXGI_MODE_ROTATION(t *testing.T) {
	if DXGI_MODE_ROTATION.DXGI_MODE_ROTATION_UNSPECIFIED != 0 {
		t.Error("DXGI_MODE_ROTATION_UNSPECIFIED should be 0")
	}
	if DXGI_MODE_ROTATION.DXGI_MODE_ROTATION_IDENTITY != 1 {
		t.Error("DXGI_MODE_ROTATION_IDENTITY should be 1")
	}
	if DXGI_MODE_ROTATION.DXGI_MODE_ROTATION_ROTATE90 != 2 {
		t.Error("DXGI_MODE_ROTATION_ROTATE90 should be 2")
	}
}

func TestDXGI_USAGE_Constants(t *testing.T) {
	if DXGI_USAGE_SHADER_INPUT != 16 {
		t.Error("DXGI_USAGE_SHADER_INPUT should be 16")
	}
	if DXGI_USAGE_RENDER_TARGET_OUTPUT != 32 {
		t.Error("DXGI_USAGE_RENDER_TARGET_OUTPUT should be 32")
	}
}
