package dxgi

type dxgiDebugRloFlags struct {
	DXGI_DEBUG_RLO_SUMMARY         uint32
	DXGI_DEBUG_RLO_DETAIL          uint32
	DXGI_DEBUG_RLO_IGNORE_INTERNAL uint32
	DXGI_DEBUG_RLO_ALL             uint32
}
type dxgiInfoQueueMessageCategory struct {
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_UNKNOWN               uint32
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_MISCELLANEOUS         uint32
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_INITIALIZATION        uint32
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_CLEANUP               uint32
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_COMPILATION           uint32
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_STATE_CREATION        uint32
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_STATE_SETTING         uint32
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_STATE_GETTING         uint32
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_RESOURCE_MANIPULATION uint32
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_EXECUTION             uint32
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_SHADER                uint32
}
type dxgiInfoQueueMessageSeverity struct {
	DXGI_INFO_QUEUE_MESSAGE_SEVERITY_CORRUPTION uint32
	DXGI_INFO_QUEUE_MESSAGE_SEVERITY_ERROR      uint32
	DXGI_INFO_QUEUE_MESSAGE_SEVERITY_WARNING    uint32
	DXGI_INFO_QUEUE_MESSAGE_SEVERITY_INFO       uint32
	DXGI_INFO_QUEUE_MESSAGE_SEVERITY_MESSAGE    uint32
}

var DXGI_DEBUG_RLO_FLAGS = dxgiDebugRloFlags{
	DXGI_DEBUG_RLO_SUMMARY:         0,
	DXGI_DEBUG_RLO_DETAIL:          1,
	DXGI_DEBUG_RLO_IGNORE_INTERNAL: 2,
	DXGI_DEBUG_RLO_ALL:             3,
}
var DXGI_INFO_QUEUE_MESSAGE_CATEGORY = dxgiInfoQueueMessageCategory{
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_UNKNOWN:               0,
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_MISCELLANEOUS:         1,
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_INITIALIZATION:        2,
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_CLEANUP:               3,
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_COMPILATION:           4,
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_STATE_CREATION:        5,
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_STATE_SETTING:         6,
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_STATE_GETTING:         7,
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_RESOURCE_MANIPULATION: 8,
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_EXECUTION:             9,
	DXGI_INFO_QUEUE_MESSAGE_CATEGORY_SHADER:                10,
}
var DXGI_INFO_QUEUE_MESSAGE_SEVERITY = dxgiInfoQueueMessageSeverity{
	DXGI_INFO_QUEUE_MESSAGE_SEVERITY_CORRUPTION: 0,
	DXGI_INFO_QUEUE_MESSAGE_SEVERITY_ERROR:      1,
	DXGI_INFO_QUEUE_MESSAGE_SEVERITY_WARNING:    2,
	DXGI_INFO_QUEUE_MESSAGE_SEVERITY_INFO:       3,
	DXGI_INFO_QUEUE_MESSAGE_SEVERITY_MESSAGE:    4,
}

type DXGI_INFO_QUEUE_FILTER struct {
	AllowList DXGI_INFO_QUEUE_FILTER_DESC
	DenyList  DXGI_INFO_QUEUE_FILTER_DESC
}
type DXGI_INFO_QUEUE_FILTER_DESC struct {
	NumCategories uint32
	CategoryList  *uint32
	NumSeverities uint32
	SeverityList  *uint32
	NumIDs        uint32
	IDList        *uint32
}
type DXGI_INFO_QUEUE_MESSAGE struct {
	Producer              DXGI_DEBUG_ID
	Category              uint32
	Severity              uint32
	ID                    uint32
	Description           *[]byte
	DescriptionByteLength SIZE_T
}
